// client/src/services/mockData.js

export const mockCertifyingBodies = [
  {
    id: 'a0000000-0000-0000-0000-000000000001',
    name: 'Islamic Food and Nutrition Council of America',
    short_code: 'IFANCA',
    country: 'United States',
    website_url: 'https://www.ifanca.org',
    is_globally_recognized: true
  },
  {
    id: 'a0000000-0000-0000-0000-000000000002',
    name: 'Halal Monitoring Committee',
    short_code: 'HMC',
    country: 'United Kingdom',
    website_url: 'https://halalhmc.org',
    is_globally_recognized: true
  },
  {
    id: 'a0000000-0000-0000-0000-000000000003',
    name: 'Jabatan Kemajuan Islam Malaysia',
    short_code: 'JAKIM',
    country: 'Malaysia',
    website_url: 'https://www.halal.gov.my',
    is_globally_recognized: true
  },
  {
    id: 'a0000000-0000-0000-0000-000000000004',
    name: 'South African National Halaal Authority',
    short_code: 'SANHA',
    country: 'South Africa',
    website_url: 'https://www.sanha.org.za',
    is_globally_recognized: true
  },
  {
    id: 'a0000000-0000-0000-0000-000000000005',
    name: 'Majlis Ugama Islam Singapura',
    short_code: 'MUIS',
    country: 'Singapore',
    website_url: 'https://www.muis.gov.sg',
    is_globally_recognized: true
  },
  {
    id: 'a0000000-0000-0000-0000-000000000006',
    name: 'Halal Food Council of North America',
    short_code: 'HFCAA',
    country: 'United States & Canada',
    website_url: 'https://www.halalcouncil.org',
    is_globally_recognized: true
  }
];

export const mockVenues = [
  {
    id: 'b0000000-0000-0000-0000-000000000001',
    name: 'Al-Madina Artisan Prime Steakhouse',
    slug: 'al-madina-artisan-prime-steakhouse',
    venue_type: 'RESTAURANT',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: 'Premier dry-aged A5 Halal Wagyu cuts, certified hand-slaughtered beef, strictly alcohol-free culinary cellar, and dedicated kitchen prep facilities.',
    address: '450 Lexington Avenue, Midtown',
    city: 'New York',
    state: 'NY',
    postal_code: '10017',
    country: 'United States',
    latitude: 40.7527,
    longitude: -73.9772,
    phone_number: '+1 (212) 555-0199',
    website_url: 'https://almadinasteak.example.com',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: true,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.95,
    review_count: 84,
    certifying_body_code: 'IFANCA',
    certifying_body_name: 'Islamic Food and Nutrition Council of America',
    active_certificate: {
      certificate_number: 'IFANCA-USA-2026-9812A',
      issued_date: '2026-01-15',
      expiration_date: '2027-01-14',
      document_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1000&auto=format&fit=crop&q=80',
      ai_confidence_score: 98.4,
      ai_raw_extraction: {
        is_valid_halal_certificate: true,
        confidence_score: 98.4,
        extracted_venue_name: 'Al-Madina Artisan Prime Steakhouse',
        venue_name_matches: true,
        certifying_body_name: 'Islamic Food and Nutrition Council of America (IFANCA)',
        certificate_id: 'IFANCA-USA-2026-9812A',
        issue_date: '2026-01-15',
        expiration_date: '2027-01-14',
        is_expired: false,
        detected_flags: [],
        summary_explanation: 'Official holographic IFANCA accreditation seal confirmed. Full scope covers hand-slaughtered beef and poultry operations. Zero cross-contamination issues identified.'
      }
    }
  },
  {
    id: 'b0000000-0000-0000-0000-000000000002',
    name: 'Saffron & Cardamom Botanical Cafe',
    slug: 'saffron-cardamom-botanical-cafe',
    venue_type: 'CAFE',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: 'Artisanal specialty coffee roastery, Persian spiced pastries, organic brioche French toasts, and dedicated female and male prayer spaces.',
    address: '28 Marylebone High Street',
    city: 'London',
    state: 'Greater London',
    postal_code: 'W1U 4PX',
    country: 'United Kingdom',
    latitude: 51.5204,
    longitude: -0.1517,
    phone_number: '+44 20 7946 0912',
    website_url: 'https://saffroncardamom.example.com',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: true,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.88,
    review_count: 112,
    certifying_body_code: 'HMC',
    certifying_body_name: 'Halal Monitoring Committee',
    active_certificate: {
      certificate_number: 'HMC-UK-CERT-8841-B',
      issued_date: '2026-02-01',
      expiration_date: '2027-01-31',
      document_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
      ai_confidence_score: 97.2,
      ai_raw_extraction: {
        is_valid_halal_certificate: true,
        confidence_score: 97.2,
        extracted_venue_name: 'Saffron & Cardamom Botanical Cafe',
        venue_name_matches: true,
        certifying_body_name: 'Halal Monitoring Committee UK (HMC)',
        certificate_id: 'HMC-UK-CERT-8841-B',
        issue_date: '2026-02-01',
        expiration_date: '2027-01-31',
        is_expired: false,
        detected_flags: [],
        summary_explanation: 'HMC full-time inspector stamp confirmed. Valid registration code verified against active UK registry.'
      }
    }
  },
  {
    id: 'b0000000-0000-0000-0000-000000000003',
    name: 'Istanbul Grand Bazaar Artisan Bakery',
    slug: 'istanbul-grand-bazaar-bakery',
    venue_type: 'BAKERY',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: 'Freshly baked Antep pistachio baklava, warm simit, authentic kunefe with zero animal rennet or gelatin adulterants, certified 100% Halal dairy.',
    address: '1088 Queen Street West',
    city: 'Toronto',
    state: 'ON',
    postal_code: 'M6J 1H8',
    country: 'Canada',
    latitude: 43.6441,
    longitude: -79.4186,
    phone_number: '+1 (416) 555-8371',
    website_url: 'https://istanbulgrandbakery.example.com',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: false,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.92,
    review_count: 67,
    certifying_body_code: 'HFCAA',
    certifying_body_name: 'Halal Food Council of North America'
  },
  {
    id: 'b0000000-0000-0000-0000-000000000004',
    name: 'Sultans Pitmaster Smokehouse & Halal BBQ',
    slug: 'sultans-pitmaster-halal-bbq',
    venue_type: 'RESTAURANT',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: '16-hour hickory wood oak smoked USDA Prime beef briskets, lamb ribs, burnt ends, and house-made barbecue glazes crafted without cooking wines.',
    address: '835 North Michigan Avenue',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60611',
    country: 'United States',
    latitude: 41.8986,
    longitude: -87.6241,
    phone_number: '+1 (312) 555-4421',
    website_url: 'https://sultansbbq.example.com',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: true,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.86,
    review_count: 145,
    certifying_body_code: 'IFANCA',
    certifying_body_name: 'Islamic Food and Nutrition Council of America'
  },
  {
    id: 'b0000000-0000-0000-0000-000000000005',
    name: 'Nusantara Heritage Kitchen & Cafe',
    slug: 'nusantara-heritage-kitchen',
    venue_type: 'CAFE',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: 'Authentic Malay and Peranakan gastronomy, Beef Rendang Tok, Nasi Lemak Royal, JAKIM certified kitchen pipeline with dedicated prayer amenities.',
    address: 'Jalan Bukit Bintang, Golden Triangle',
    city: 'Kuala Lumpur',
    state: 'Wilayah Persekutuan',
    postal_code: '55100',
    country: 'Malaysia',
    latitude: 3.1479,
    longitude: 101.7101,
    phone_number: '+60 3-2148 8899',
    website_url: 'https://nusantaraheritage.example.com',
    image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: true,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.97,
    review_count: 230,
    certifying_body_code: 'JAKIM',
    certifying_body_name: 'Jabatan Kemajuan Islam Malaysia',
    active_certificate: {
      certificate_number: 'JAKIM-MAL-2026-55919',
      issued_date: '2026-03-10',
      expiration_date: '2028-03-09',
      document_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1000&auto=format&fit=crop&q=80',
      ai_confidence_score: 99.1,
      ai_raw_extraction: {
        is_valid_halal_certificate: true,
        confidence_score: 99.1,
        extracted_venue_name: 'Nusantara Heritage Kitchen & Cafe',
        venue_name_matches: true,
        certifying_body_name: 'Jabatan Kemajuan Islam Malaysia (JAKIM)',
        certificate_id: 'JAKIM-MAL-2026-55919',
        issue_date: '2026-03-10',
        expiration_date: '2028-03-09',
        is_expired: false,
        detected_flags: [],
        summary_explanation: 'JAKIM sovereign seal verified. QR checksum matches official Halal Malaysia Directory. 100% compliance certified.'
      }
    }
  },
  {
    id: 'b0000000-0000-0000-0000-000000000006',
    name: 'Medina Gourmet Wagyu & Halal Butcher',
    slug: 'medina-gourmet-halal-butcher',
    venue_type: 'BUTCHER_SHOP',
    halal_classification: 'FULL_HALAL_MONITORED',
    description: 'Specialty artisanal butchery offering HMC monitored hand-slaughtered British grass-fed beef, Australian Wagyu cuts, free-range poultry, and vacuum marinades.',
    address: '144 Edgware Road',
    city: 'London',
    state: 'Greater London',
    postal_code: 'W2 2DZ',
    country: 'United Kingdom',
    latitude: 51.5168,
    longitude: -0.1633,
    phone_number: '+44 20 7262 0188',
    website_url: 'https://medinabutcher.example.com',
    image_url: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=1000&auto=format&fit=crop&q=80',
    is_alcohol_free: true,
    has_prayer_space: false,
    has_separate_prep_area: true,
    is_hand_slaughtered_only: true,
    verification_status: 'AI_VERIFIED',
    average_rating: 4.91,
    review_count: 98,
    certifying_body_code: 'HMC',
    certifying_body_name: 'Halal Monitoring Committee'
  }
];

export const mockMenuItems = [
  {
    id: 'd1',
    name: 'A5 Miyazaki Wagyu Ribeye (12oz)',
    description: 'Certified 100% Halal Japanese Wagyu, BMS 11, seared over Japanese white binchotan charcoal with smoked Maldon salt.',
    price: 135.00,
    category: 'Steaks & Mains',
    is_halal_certified: true,
    contains_alcohol: false
  },
  {
    id: 'd2',
    name: 'Dry-Aged Tomahawk Steak (38oz)',
    description: '45-day Himalayan salt cave dry-aged black Angus ribeye, hand-slaughtered, basted with rosemary brown butter.',
    price: 165.00,
    category: 'Steaks & Mains',
    is_halal_certified: true,
    contains_alcohol: false
  },
  {
    id: 'd3',
    name: 'Zero-Proof Pomegranate Cardamom Elixir',
    description: 'Cold-pressed Persian pomegranate juice, smoked cedar bitters (alcohol-free botanical extraction), and bubbly soda.',
    price: 14.00,
    category: 'Artisan Mocktails',
    is_halal_certified: true,
    contains_alcohol: false
  }
];

export const mockReviews = [
  {
    id: 'e1',
    user_name: 'Tariq Al-Mansoor',
    rating: 5,
    comment: 'Exceptional dining experience! The IFANCA certificate is framed right at the entrance, and the staff explained their meat provenance with total transparency.',
    halal_authenticity_rating: 5
  },
  {
    id: 'e2',
    user_name: 'Sister Maryam K.',
    rating: 5,
    comment: 'Peaceful atmosphere, zero alcohol anywhere on premises, and a clean dedicated prayer area with wudu facilities. May Allah bless this establishment.',
    halal_authenticity_rating: 5
  }
];
